### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by brandondrew** [rethinkdb/cats-of-instagram#3]
Sorry, I couldn't find a better place to post this—it's not actually a bug in this code, but a bad link on the blog entry that is supposed to point to this repo.  Instead of linking here it links to http://rethinkdb.com/rethinkdb/cats-of-instagram, which renders a 404 error.

If there was a better place to report this problem, and I missed it, please let me know.  Thanks.

**Comment by danielmewes** [comment]
Thanks for reporting this @brandondrew .

Pinging @segphault, @dalanmiller

**Comment by segphault** [comment]
Thanks for bringing the issue to our attention. I fixed the link and it should show up correctly on the site soon.
